version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: queue-learning
    volumes:
      - ./:/var/www/html
    networks:
      - rede1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rede1

  nginx:
    image: nginx:1.27
    container_name: nginx
    depends_on:
      - app
    links:
      - app
    ports:
      - "8181:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/code
    networks:
      - rede1

  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - rede1
    ports:
      - "3306:3306"

volumes:
  database_data:

networks:
  rede1:
    driver: bridge
